/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by CobiGen.
 */

export class FieldEto {
  readonly fieldName?: string;
  readonly fieldType?: string;
}
