/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by CobiGen.
 */

export interface MatcherEto {
readonly inputToMatch?: object;
readonly type?: string;
readonly value?: string;
readonly accumulationType?: string;
}
