/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by CobiGen.
 */

export interface MergerEto {
  readonly baseContent: string;
  readonly patchContent: string;
  readonly patchOverrides: boolean;
}
