/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by CobiGen.
 */

export interface MergerEto {
readonly basePath?: string;
readonly patchPath?: string;
readonly targetCharset?: string;
}
