/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by CobiGen.
 */

export class ModelEto {
  readonly input: string;

  public constructor(input: string) {
    this.input = input;
  }
}
