/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by CobiGen.
 */

export interface ModelEto {
readonly fileType?: string;
readonly fileName?: string;
readonly Fields?: object;
readonly Imports?: object;
}
