/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by CobiGen.
 */

export class MergerEto {
  readonly baseContent: string;
  readonly patchContent: string;
  readonly patchOverrides: boolean;

  public constructor(
    baseContent: string,
    patchContent: string,
    patchOverrides: boolean,
  ) {
    this.baseContent = baseContent;
    this.patchContent = patchContent;
    this.patchOverrides = patchOverrides;
  }
}
